In [1]:
import os
os.listdir()

['.489614.padl',
 '.anaconda',
 '.android',
 '.atom',
 '.bash_history',
 '.bash_profile',
 '.bash_profile-anaconda.bak',
 '.bash_profile.backup',
 '.bash_profile.pysave',
 '.bash_sessions',
 '.bitnami',
 '.cache',
 '.CFUserTextEncoding',
 '.conda',
 '.condarc',
 '.config',
 '.continuum',
 '.dropbox',
 '.DS_Store',
 '.eclipse',
 '.gem',
 '.git',
 '.gitignore',
 '.gradle',
 '.IdentityService',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lesshst',
 '.local',
 '.m2',
 '.matplotlib',
 '.metadata',
 '.mono',
 '.mysql_history',
 '.npm',
 '.nuget',
 '.octave_hist',
 '.oracle_jre_usage',
 '.p2',
 '.pencil',
 '.pgadmin',
 '.project',
 '.python_history',
 '.QtWebEngineProcess',
 '.Rapp.history',
 '.RData',
 '.Rhistory',
 '.rstudio-desktop',
 '.ServiceHub',
 '.settings',
 '.spyder',
 '.spyder-py3',
 '.sqldeveloper',
 '.ssh',
 '.subversion',
 '.templateengine',
 '.ti',
 '.tooling',
 '.Trash',
 '.vagrant',
 '.vagrant.d',
 '.viminfo',
 '2313131.txt',
 '424-spring2017-project0',
 '

In [10]:
import numpy
n=numpy.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [11]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
m=numpy.asarray([[123,12,13,12,11],[],[]])
m

array([list([123, 12, 13, 12, 11]), list([]), list([])], dtype=object)

In [13]:
print(m)

[list([123, 12, 13, 12, 11]) list([]) list([])]


In [14]:
import cv2
im_g=cv2.imread("smallgray.png",0)#0 means blue,yellow,green
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
im_g=cv2.imread("smallgray.png",1)#means 1 for blue, 1 for yellow, 1 for green
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [16]:
cv2.imwrite("newsmallgray.png",im_g)


True

In [17]:
im_g[:,2:3]

array([[[104, 104, 104]],

       [[255, 255, 255]],

       [[255, 255, 255]]], dtype=uint8)

In [18]:
im_g[2,4]

array([182, 182, 182], dtype=uint8)

In [19]:
for i in im_g:
    print(i)

[[187 187 187]
 [158 158 158]
 [104 104 104]
 [121 121 121]
 [143 143 143]]
[[198 198 198]
 [125 125 125]
 [255 255 255]
 [255 255 255]
 [147 147 147]]
[[209 209 209]
 [134 134 134]
 [255 255 255]
 [ 97  97  97]
 [182 182 182]]


In [22]:
ims=numpy.hstack((im_g,im_g,im_g))
print(ims)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]
  [187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]
  [187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]
  [198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]
  [198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]
  [209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]
  [209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [23]:
numpy.vsplit(ims,3)

[array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143],
         [187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143],
         [187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]]], dtype=uint8), array([[[198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147],
         [198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147],
         [198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147]]], dtype=uint8), array([[[209, 209, 209],
         [134, 134, 134],
         [255, 255, 255],
         [ 97,  97,  97],
         [182, 182, 182],
         [209, 209, 209],
         [134, 134, 134],
        

In [25]:
import folium

In [28]:
map_osm=folium.Map(location=[37.7529648, -122.4317141])
map_osm

In [29]:
map_1=folium.Map(location=[45.372,-121.6972],zoom_start=12,tiles='Stamen Terrain')
folium.Marker([45.3288,-121.6625],popup="Mt.Hood Meadows").add_to(map_1)
folium.Marker([45.3311,-121.7113],popup='Timberline lodge').add_to(map_1)
map_1

In [34]:
map_2=folium.Map(location=[45.5236,-122.6750],zoom_start=10,tiles='Stamen Toner')
folium.Marker([45.5244,-122.6699],popup="The waterfront").add_to(map_2)
folium.CircleMarker([45.5215,-122.6261],Radius=500,popup='Laurelhurst Park',color='#3186cc',fill_color='#3186cc',).add_to(map_2)
map_2

In [38]:
map_3=folium.Map(location=[46.8527,-121.7649],zoom_start=12,tiles='Stamen Terrain')
folium.Marker([46.8354,-121.7325],popup="camp muir").add_to(map_3)
map_3.add_child(folium.LatLngPopup())
map_3.add_child(folium.ClickForMarker(popup="Waypoint"))


map_3

In [52]:
import pandas,folium
df=pandas.read_csv("Volcanoes_USA.txt")
malp=folium.Map(location=[45.372,-121.697],zoom_start=5,tiles='Stamen Terrain')

for la,lo,name in zip(df['LAT'],df['LON'],df['NAME']):
    folium.Marker(location=[la,lo],popup=name).add_to(malp)
malp

In [ ]:
import pandas,folium
df=pandas.read_csv("Volcanoes_USA.txt")
map=folium.Map(location=[df['LAT'].mean(),df['LON'].mean()],zoom_start=5,tiles='Stamen Terrain')

def color(elev):
    minimum=int(min(df['ELEV']))
    step=int((max(df['ELEV'])-min(df['ELEV']))/3)
    if elev in range(minimum,minimum+step):
        col='green'
    elif elev in range(minimum+step,minimum+step*2):
        col='orange'
    else:
        col='red'
    return col

fg=folium.FeatureGroup(name="Volcano Locations")

for la,lo,name,elev in zip(df['LAT'],df['LON'],df['NAME'],df['ELEV']):
    fg.add_child(folium.Marker(location=[la,lo],popup=name,icon=folium.ICON(color(elev)))
map.add_child(fg)
map.add_child(folium.GeoJson(data=open('world_population.json'),
                            name='world Population',
                            style_function=lambda x:{'fillcolor:'green' if x['properties']['POP2005']<10000})
                                                     
map.add_child(folium.layerControl())
map                                                     